### ISSUE TITLE
Accessing server

### ISSUE THREAD

**Issue by mapmeld** [Kharatsa/odkaggregate#1]
Hi,
I'm using this to try out ODK on my computer. I was able to create a container, and when I run `docker exec CONTAINER_NAME curl http://localhost:8080` it shows me the Tomcat default start

I'm not able to `curl http://localhost:8080/ODKAggregate` - that gives me the 404 page

What's the best way to look and see ODK starting up inside the container?

Additional info: I have `lib/mysql-connector-java-5.1.38-bin.jar` but I don't think I have the WAR file

**Comment by seanjh** [comment]
This is immediately after creating the container? Did you ever issue the `docker run` command?

The container needs `docker run` executed at least once before the ODK Aggregate app will be accessible. Certain setup and installation steps are deferred until that first run, in order to isolate credentials from the hosted image. That one time setup logic all lives in [run.sh](https://github.com/Kharatsa/odkaggregate/blob/master/run.sh). (this is similar to the way the MySQL container, for example, creates databases as a side effect of its `docker run`)

`ODK_Aggregate.war` is included in the build [on Docker Hub](https://hub.docker.com/r/kharatsa/odkaggregate/), and does not need to be added separately assuming you're doing `docker pull kharatsa/odkaggregate`. The [Dockerfile](https://github.com/Kharatsa/odkaggregate/blob/master/Dockerfile) also downloads and [installs ConnectorJ](https://github.com/Kharatsa/odkaggregate/blob/master/Dockerfile#L19) as part of the build process, so that will be included in the image.

**Comment by mapmeld** [comment]
Oh ok I was running it from the repo and not `docker pull`-ing, so the COPY commands didn't work like they were supposed to.  I also had to set up the MySQL container for everything to connect.

Thanks!
